config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'sales/new'
  get 'sales', to: 'sales#index'
  post 'sales', to: 'sales#create'
  get 'sales/:id', to: 'sales#done', as: 'sales_done'
  get 'sales/:id', to: 'sales#show', as: 'sale'
end


  #get 'posts/new'
  #post 'posts', to: 'posts#create'
  #get 'posts/:id', to: 'posts#show', as: 'post'

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/sale.rb
class Sale < ApplicationRecord
	validates :cod, uniqueness: true
	validates :detail, presence: true
	validates :category, inclusion: { in: %w(uno dos tres cuatro cinco) }
	validates :value, numericality: {only_integer: true, greater_than: 0}
	validates :discount, numericality: {only_integer: true, less_than_or_equal_to: 40, greater_than: 0}

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/sales_controller.rb
class SalesController < ApplicationController
  def index
  	@sales = Sale.all
  end	

  def new
  	@sale = Sale.new
  end

  def show
  	@sale = Sale.find(params[:id])
  end

  def create
  	@sale = Sale.new(sale_params)
  	@sale.total = @sale.value * (1 - (@sale.discount.to_f/100))
  	@sale.cod = SecureRandom.hex
  	if @sale.tax == 0
  		@sale.total *= 1.19
  		@sale.tax = 19
  	else
  		@sale.tax = 0
  	end
  	if @sale.save
  		redirect_to sales_done_path(@sale)
  	else
  		redirect_to sales_new_path
  	end
  end

  def done
  	@sale = Sale.find(params[:id])
  end

  private

  def sale_params
  	params.require(:sale).permit(:detail, :category, :value, :discount, :tax, :total)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FormsValidations</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/sales/_form.html.erb
<%= form_with model: @sale, local: true do |f| %>
      <%= f.label :detail, "Detalle" %>
      <%= f.text_area :detail %>
      <%= f.label :category, "Categoria" %>
      <%= f.text_field :category %>
      <%= f.label :value, "Valor venta" %>
      <%= f.number_field :value %>
      <%= f.label :discount, "Valor descuento" %>
      <%= f.number_field :discount %>
      <%= f.label :tax, "Exento de IVA" %>
      <%= f.check_box :tax %>
      <%= f.submit "Enviar" %>
<% end %>

app/views/sales/done.html.erb
<h1>El registro fue almacenado con éxito!</h1>
<p>Detalle: <%= @sale.detail %></p>
<p>Categoria: <%= @sale.category %></p>
<p>Valor: <%= @sale.value %></p>
<p>Descuento: <%= @sale.discount %></p>
<p>Valor IVA: <%= @sale.tax %></p>
<p>Valor Total: <%= @sale.total %></p>
<p><%= link_to "Volver", sales_path %></p>

app/views/sales/index.html.erb
<% @sales.each do |sale| %>
	<p>Detalle: <%= sale.detail %></p>
	<p>Categoria: <%= sale.category %></p>
	<p>Valor: <%= sale.value %></p>
	<p>Descuento: <%= sale.discount %></p>
	<p>Valor IVA: <%= sale.tax %></p>
	<p>Valor Total: <%= sale.total %></p>
<% end %>

<h2><%= link_to "Crear Nueva venta", sales_new_path %></h2>

app/views/sales/new.html.erb
<%= render "form" %>

app/views/sales/show.html.erb
<h1>SHOW VENTA <%= @sale.cod %></h1>
<p>Detalle: <%= @sale.detail %></p>
<p>Categoria: <%= @sale.category %></p>
<p>Valor: <%= @sale.value %></p>
<p>Descuento: <%= @sale.discount %></p>
<p>Valor IVA: <%= @sale.tax %></p>
<p>Valor Total: <%= @sale.total %></p>